### ISSUE TITLE
using python

### ISSUE THREAD

**Issue by tambatd** [jbjd/Python-Minifier#1]
should be using a better language with TYPES

**Comment by jbjd** [comment]
If you can implement a Python parser and unparser thats better than Python's standard library be my guest

**Comment by tambatd** [comment]
going to write this in zig

**Comment by tambatd** [comment]
i'm be real with u chief, i'm not doing this 
![image](https://github.com/user-attachments/assets/94c0a6bb-03e7-4b2b-8afb-4138cfa2fe33)
